### ISSUE TITLE
Thanks for the effort!!!

### ISSUE THREAD

**Issue by felipetesc** [oooutlk/tcltk#1]
Thanks for the effort of creating this bindings for TCLTK. There are several reasons why Python people are using Tkinter.  I've being in the search for a retained mode GUI library for Rust for quite some time. All the previous attempts to create TCLTK bindings for Rust ended, what's is sad.  

What kind of help do you need in terms of keeping this project up and running ?

And I'm glad I discovered this project one day after the first commit!

**Comment by oooutlk** [comment]
I’m glad too that this project may help you. It may evolve with responses from real-world use cases, which I haven’t seen yet. The goal: to make both Rustaceans and Tk-ers happy ^_^

**Comment by felipetesc** [comment]
> I’m glad too that this project may help you. It may evolve with responses from real-world use cases, which I haven’t seen yet. The goal: to make both Rustaceans and Tk-ers happy ^_^

Worth nothing to mention that people from Deno, which is based on Rust and V8, are looking for a GUI library as well. I'm receiveng notiffications from:   [Deno Standard GUI](https://github.com/denoland/deno/discussions/3234) . You could tell them about your job as it could boost your it
